wandb_version: 1

n_steps:
  desc: null
  value: 2048
batch_size:
  desc: null
  value: 64
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.00025
ent_coef:
  desc: null
  value: 0.01
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
gae_lambda:
  desc: null
  value: 0.95
n_epochs:
  desc: null
  value: 4
clip_range:
  desc: null
  value: 0.2
clip_range_vf:
  desc: null
  value: null
verbose:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705334790.801491
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.16.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
